/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl */

#ifndef _Included_edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl
#define _Included_edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl
 * Method:    createF2mPoint
 * Signature: (J[B[B[Z)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl_createF2mPoint
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbooleanArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl
 * Method:    createRandomF2mPoint
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl_createRandomF2mPoint
  (JNIEnv *, jobject, jlong, jint, jbooleanArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl
 * Method:    deletePointF2m
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_dlog_miracl_ECF2mPointMiracl_deletePointF2m
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
