/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_protocols_yao_primitives_KProbeResistantMatrixBuilder */

#ifndef _Included_edu_biu_protocols_yao_primitives_KProbeResistantMatrixBuilder
#define _Included_edu_biu_protocols_yao_primitives_KProbeResistantMatrixBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_protocols_yao_primitives_KProbeResistantMatrixBuilder
 * Method:    createMatrix
 * Signature: (III)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_biu_protocols_yao_primitives_KProbeResistantMatrixBuilder_createMatrix
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
