/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_PerfectUniversalHash_EvaluationHashFunction */

#ifndef _Included_edu_biu_scapi_primitives_PerfectUniversalHash_EvaluationHashFunction
#define _Included_edu_biu_scapi_primitives_PerfectUniversalHash_EvaluationHashFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_PerfectUniversalHash_EvaluationHashFunction
 * Method:    initHash
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_PerfectUniversalHash_EvaluationHashFunction_initHash
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     edu_biu_scapi_primitives_PerfectUniversalHash_EvaluationHashFunction
 * Method:    computeFunction
 * Signature: (J[BI[BI)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_PerfectUniversalHash_EvaluationHashFunction_computeFunction
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
