/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCryptopp */

#ifndef _Included_CollisionResistantHash
#define _Included_CollisionResistantHash
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash
 * Method:    createHash
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash_createHash
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash
 * Method:    algName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash_algName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash
 * Method:    updateHash
 * Signature: (J[BJ)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash_updateHash
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash
 * Method:    finalHash
 * Signature: (J[BJ)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash_finalHash
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash
 * Method:    deleteHash
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_hash_cryptopp_CryptoPpCollResHash_deleteHash
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif