/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp */

#ifndef _Included_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp
#define _Included_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp
 * Method:    createDlogZp
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp_createDlogZp
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp
 * Method:    inverseElement
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp_inverseElement
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp
 * Method:    exponentiateElement
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp_exponentiateElement
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp
 * Method:    multiplyElements
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp_multiplyElements
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp
 * Method:    validateZpGroup
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp_validateZpGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp
 * Method:    validateZpGenerator
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp_validateZpGenerator
  (JNIEnv *, jobject, jlong);

JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp_validateZpElement
  (JNIEnv *, jobject, jlong group, jlong element);
/*
 * Class:     edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp
 * Method:    deleteDlogZp
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_dlog_cryptopp_CryptoPpDlogZp_deleteDlogZp
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
