/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpTrapdoorPermutation */

#ifndef _Included_edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpTrapdoorPermutation
#define _Included_edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpTrapdoorPermutation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpTrapdoorPermutation
 * Method:    createTP
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_primitives_trapdoor_1permutation_cryptopp_CryptoPpTrapdoorPermutation_createTP
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpTrapdoorPermutation
 * Method:    computeTP
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_trapdoor_1permutation_cryptopp_CryptoPpTrapdoorPermutation_computeTP
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpTrapdoorPermutation
 * Method:    invertTP
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_primitives_trapdoor_1permutation_cryptopp_CryptoPpTrapdoorPermutation_invertTP
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpTrapdoorPermutation
 * Method:    deleteTP
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_trapdoor_1permutation_cryptopp_CryptoPpTrapdoorPermutation_deleteTP
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpRSAPermutation
 * Method:    initRSA
 * Signature: (J[B[B[B)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_primitives_trapdoor_1permutation_cryptopp_CryptoPpRSAPermutation_initRSA
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpRSAPermutation
 * Method:    loadRSAName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_biu_scapi_primitives_trapdoor_1permutation_cryptopp_CryptoPpRSAPermutation_loadRSAName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_primitives_trapdoor_permutation_cryptopp_CryptoPpRabinPermutation
 * Method:    loadRabinName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_biu_scapi_primitives_trapdoor_1permutation_cryptopp_CryptoPpRabinPermutation_loadRabinName
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
