/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit */

#ifndef _Included_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
#define _Included_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_SCAPI_NATIVE_KEY_SIZE
#define edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_SCAPI_NATIVE_KEY_SIZE 16L
/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    createGarbledcircuit
 * Signature: (Ljava/lang/String;ZZ[B)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_createGarbledcircuit
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    getOutputIndicesArray
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_getOutputIndicesArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    getInputIndicesArray
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_getInputIndicesArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    getNumOfInputsForEachParty
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_getNumOfInputsForEachParty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    setGarbleTables
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_setGarbleTables
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    getGarbleTables
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_getGarbleTables
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    getTranslationTable
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_getTranslationTable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    setTranslationTable
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_setTranslationTable
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    garble
 * Signature: ([B[B[B[BJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_garble
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jlong);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    compute
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_compute
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    verify
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_verify
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    internalVerify
 * Signature: (J[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_internalVerify
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    translate
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_translate
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    verifyTranslate
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_verifyTranslate
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    verifyTranslationTable
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_verifyTranslationTable
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit
 * Method:    deleteCircuit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_biu_scapi_circuits_fastGarbledCircuit_ScNativeGarbledBooleanCircuit_deleteCircuit
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
